### ISSUE TITLE
Reading .so files on iOS cleo

### ISSUE THREAD

**Issue by Jdoendmdxm** [squ1dd13/CLEO-iOS#15]
Hi

do you know how to read the .so files on iOS Cleo GTA sa because some mods come with the .so file format?

**Comment by squ1dd13** [comment]
Mods with .so files contain compiled code that will only run on Android. Please can you add a link to the mod that you're trying to use?

**Comment by Jdoendmdxm** [comment]
> Most mods with .so files contain compiled code that will only run on Android. Please can you add a link to the mod that you're trying to use?

I was trying to do the restore cut songs mod and this is the link that comes with the .so file


https://www.mediafire.com/file/q04yotxtis22zvh/Restored+Cut+Songs+Mobile.7z/file

**Comment by Jdoendmdxm** [comment]
Squ1dd13 did you manage to get the .so file to work on iOS version of GTA sa?

**Comment by squ1dd13** [comment]
Sorry for the late reply. This mod won't work because the .so file is incompatible with iOS.
