### ISSUE TITLE
Add support to A12 devices

### ISSUE THREAD

**Issue by Yamino-Kageto** [Squ1dd13/CLEO-iOS#3]
as cydia subtrate isn't (and won't ever be) compatible with A12+ devices it would be cool if you add substitute/libhooker support.

Also libhooker does have a substrate compatibility layer. Wouldn't that be enough for your tweak?

And substrate does have its flaw, it all depends on saurik (who isn't that much available these times) to maintain it and fix its flaw like there. https://github.com/checkra1n/BugTracker/issues/533

Uncover also ditched substrate for substitute as it can achieve better stability for pwn20wnd.
Libhooker would be able to gain swift hooking function and be open source

**Comment by Squ1dd13** [comment]
I hadn't considered compatibility issues for A12+ devices, so I'll look into supporting them through the libhooker compatibility layer.

**Comment by Yamino-Kageto** [comment]
Thanks.

For libhooker you can join the sileo discord and ask coolstar directly. He does help devs which tweaks has problem running with libhooker.

**Comment by RashidFarhad** [comment]
Hi , Its Not Work For Me See The Photos 😅💔 Please Help
![Uploading 62C48DD7-2DE9-4F12-9477-87CFE07EC8CA.png…]()

**Comment by RashidFarhad** [comment]
![6A13A9DD-C556-45E9-819F-1B3052CAD216](https://user-images.githubusercontent.com/69083831/108221403-cf092880-7148-11eb-96e2-7b89f9bf3dd5.png)

**Comment by RashidFarhad** [comment]
![Uploading A59255C1-496A-4B37-AE35-DA846D078876.png…]()

**Comment by RashidFarhad** [comment]
![Uploading A91DFEF9-9EA4-4B94-851E-0D9830BFA1D7.png…]()
