### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by damorfc1** [squ1dd13/CLEO-iOS#9]
The game crashes when it loads up? I’m on version 2.02

**Comment by damorfc1** [comment]
2.02.11

**Comment by squ1dd13** [comment]
Please could you provide the `cleo.log` file and any files from Cr4shed/CrashReporter? If you don't have Cr4shed then please install it, make the game crash, and then put the crash log here.

**Comment by squ1dd13** [comment]
No input in ages, closing.
